### ISSUE TITLE
使用lora微调llama结果不对

### ISSUE THREAD

**Issue by lv-otfse** [yao8839836/kg-llm#8]
大佬，您好，我在执行python finetune_wn11.py的代码时损失函数loss很大，训练完保存的权重文件如下，而且adapter_model.bin文件的大小只有1KB，训练的结果不对。我想请教一下您什么原因，是transformers和peft版本的原因吗？我用的是transformers==4.28.0，peft==0.5.0。
![屏幕截图 2024-06-08 105246](https://github.com/yao8839836/kg-llm/assets/115402157/0b1487b0-ef4f-48b2-87cc-73138b3dc1de)
![屏幕截图 2024-06-08 105345](https://github.com/yao8839836/kg-llm/assets/115402157/da3faa34-e45c-4178-848f-77b56de168ad)
![微信图片_20240613103012](https://github.com/yao8839836/kg-llm/assets/115402157/45948d7b-d566-496a-9ecb-51fbbe767202)

**Comment by hhy-huang** [comment]
I met the same problem, but my loss was not strange. The generated responses includes instruction sentence.

**Comment by Dqasadsasadsafsasad** [comment]
我的loss和学习率在前期一直是0，正常吗，这是什么问题啊
